import "./globals.css";
import { Inter } from "next/font/google";

import "./style/assets/css/bootstrap.min.css";
import "./style/assets/css/font-awesome.min.css";
import "./style/assets/css/apexcharts.css";
import "./style/assets/css/style.css";
import "./style/assets/css/responsive.css";
import "./style/assets/css/google-font.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
